### ISSUE TITLE
sdd1_01_19_svbox

### ISSUE THREAD

**Issue by GuyliannEngels** [BioDataScience-Course/sdd_lesson#1]
Je viens d'écrire deux documents relatifs au chapitre 1 du livre SDD1. 

- sdd1_01_19_svbox.Rmd (sdd_lesson/sdd1_01/presentations/sdd1_01_19_svbox.Rmd)
- sdd1_01_19_svbox.Rmd (sdd_lesson/sdd1_01/exercises/sdd1_01_19_svbox_solution.Rmd

@RConotte et @phgrosjean, pouvez vous y jeter un coup d'oeil ? Ces exercices devraient être réalisé par les étudiants (je mets les dates à titre indicatifs)

- mons : à partir du 30 septembre 
- charleroi : à partir du 23 septembre

**Comment by phgrosjean** [comment]
Je viens de relire et j'ai fais quelques corrections.

**Comment by RConotte** [comment]
J'ai également relu les documents et fait quelques corrections.
